# https://superuser.com/questions/183870/difference-between-bashrc-and-bash-profile/183980#183980
if [ -r ~/.profile ]; then . ~/.profile; fi
case "$-" in *i*) if [ -r ~/.bashrc ]; then . ~/.bashrc; fi;; esac
