# bashrc
# Clark Fitzgerald

printf '\n    Follow the white rabbit\n\n'

if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Trying to get the files in color.
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

# added by Anaconda 1.8.0 installer
#export PATH="//anaconda/bin:$PATH"
# Set below path to use Python 2
export PATH='/Users/clark/anaconda/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/texbin'

# Add personal utilities to Python path
export PYTHONPATH="/Users/clark/projects/statsmodels"

# Make the terminal start with tmux
#if [[ ! $Term =~ screen ]]; then
#    exec tmux
#fi

# Use single $ for prompt
PS1='\w \$ '

# Aliased commands
alias tml='tmux list-sessions'
alias tma='tmux attach -t'
alias gpom='git push origin master'
