# bashrc
# Clark Fitzgerald

printf '\n    Hi Clark\n\n'

if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Trying to get the files in color.
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

# Python 2
#export PATH='/Users/clark/anaconda/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/texbin'

# Python 3
export PATH='/Users/clark/anaconda/envs/py3k/bin:/Users/clark/utils/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/texbin'

# Add personal utilities to Python path
export PYTHONPATH="/Users/clark/utils/python"

# Make the terminal start with tmux
#if [[ ! $Term =~ screen ]]; then
#    exec tmux
#fi

# Use single $ for prompt
PS1='\w \$ '

# Aliased commands
alias tml='tmux list-sessions'
alias tma='tmux attach -t'

# Enables conda install commands
alias py3k='source activate py3k'
