" Vimrc
" Clark Fitzgerald
"
" Set the colorscheme and font
"colorscheme delek
set number              " Display line numbers
"set gfn=Menlo:h14

" Tab settings
set tabstop=4
set expandtab
set softtabstop=4
set shiftwidth=4

" To use Python mode
"filetype off
"call pathogen#infect()
"call pathogen#helptags()

filetype plugin indent on
syntax on

" Keep it under 80 characters wide
" set textwidth=79

" From Practical Vim book
set history=200     " Change from 20 commands to 200 in history.

" Toggle folding with spacebar
set foldmethod=indent
nnoremap <Space> za
vnoremap <Space> zf
set foldnestmax=2

" Highlight trailing whitespace
"match Todo /\s\+$/

set tw=75


""""""""""""""""""""""""""""""""""""""""
""" Macros
""""""""""""""""""""""""""""""""""""""""

" Remove all trailing whitespace in file
let @w = ':%s/\s\+$//'


""""""""""""""""""""""""""""""""""""""""
" Lines added by the Vim-R-plugin command :RpluginConfig (2014-Oct-24 22:34):
filetype plugin on
" Change the <LocalLeader> key:
let maplocalleader = ","
" Use Ctrl+Space to do omnicompletion:
if has("gui_running")
    inoremap <C-Space> <C-x><C-o>
else
    inoremap <Nul> <C-x><C-o>
endif
" Press the space bar to send lines (in Normal mode) and selections to R:
"vmap <Space> <Plug>RDSendSelection
"nmap <Space> <Plug>RDSendLine

" Force Vim to use 256 colors if running in a capable terminal emulator:
if &term =~ "xterm" || &term =~ "256" || $DISPLAY != "" || $HAS_256_COLORS == "yes"
    set t_Co=256
endif
